### ISSUE TITLE
pinterest/official.php が PHPComatability で Warning を出している

### ISSUE THREAD

**Issue by waviaei** [inc2734/wp-share-buttons#4]
Snow Monkey v25.2.4 に対して PHPCompatibility チェックを実行したところ、PHP 8.0、8.1、8.2 全てで下記 Warning がでました。

```
FILE: /snow-monkey/vendor/inc2734/wp-share-buttons/src/view/pinterest/official.php
--------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------------------
 1 | WARNING | No PHP code was found in this file and short open tags are not allowed by this install of PHP. This file
   |         | may be using short open tags but PHP does not allow them.
--------------------------------------------------------------------------------------------------------------------------
```

https://github.com/inc2734/wp-share-buttons/blob/master/src/view/pinterest/official.php
PHPファイルですが、PHPが1行もなく、`<?php` もないことが理由のようです。

他の同様のファイルと同じように先頭に

```
<?php
/**
 * phpdoc
 */
?>
```

をつける。

もしくはファイルを削除して、https://github.com/inc2734/wp-share-buttons/blob/833a62f76650c97e2b632d9b98360f92d8582325/src/view/pinterest/pinterest.php#L6 のphpdoc コメントに該当ドキュメンテーションへのリンクの追加を書く。

```
@see https://developers.pinterest.com/docs/add-ons/save-button/
```

を行うのはどうでしょうか？

**Comment by inc2734** [comment]
今気づきました！すみません。他のサービスの `official.php` は全部 phpdoc が入っているので、それに合わせたいと思います。お知らせありがとうございます。
